// bundleLauncher(window) — generate the source of the desktop launcher script `abide bundle` emits.
//
// The launcher is a standalone Bun script written to `dist/bundle/launch.ts`. Running it boots the
// app the way the desktop bundle does (BU1, dual-mode like the CLI):
//   - `ABIDE_APP_URL` set  → thin client: point the window at that remote deployment;
//   - otherwise            → self-host: spawn `abide start` with `ABIDE_BUNDLED=1`, then point the
//     window at the local server.
//
// NATIVE WINDOWING IS BEST-EFFORT (BU1.2 is parked here): a real embedded native webview
// (WebKit / WebView2 / WebKitGTK via a Tauri-style native shell) needs a platform-native dependency
// abide does not bundle. So the launcher opens a system webview *binary* if one is on PATH, else
// falls back to the default system browser (`open` / `xdg-open` / `start`). It logs which path it
// took. The window-open is skipped when `ABIDE_BUNDLE_NO_WINDOW=1` (tests/CI) or on a headless Linux
// box (no `DISPLAY`).
//
// The declarative `BundleWindow` (title/size/menu) is embedded as a JSON literal so the artifact is
// self-contained — no import back into abide internals.

import type { BundleWindow } from "../bundle/BundleWindow.ts";

export function bundleLauncher(window: BundleWindow): string {
  const windowJson = JSON.stringify(window ?? {}, null, 2);
  return `#!/usr/bin/env bun
// GENERATED by \`abide bundle\` — MVP desktop launcher. Native windowing is BEST-EFFORT:
// opens a system webview binary if one is on PATH, else the default system browser. A real embedded
// native webview needs a platform-native shell dependency abide does not bundle (parked, BU1.2).

const WINDOW = ${windowJson};
const PORT = Number(Bun.env.PORT ?? "4321");
const REMOTE_URL = Bun.env.ABIDE_APP_URL;
const APP_URL = REMOTE_URL ?? \`http://localhost:\${PORT}\`;

// Probe PATH for a system webview binary (best-effort). Extend via ABIDE_WEBVIEW_BIN.
function probeWebview() {
  const candidates = [Bun.env.ABIDE_WEBVIEW_BIN, "webview", "webviewgtk", "wkview"].filter(Boolean);
  for (const name of candidates) {
    const found = Bun.which(name);
    if (found) return found;
  }
  return undefined;
}

function shouldOpenWindow() {
  if (Bun.env.ABIDE_BUNDLE_NO_WINDOW === "1") return false;
  if (process.platform === "linux" && !Bun.env.DISPLAY) return false;
  return true;
}

// Best-effort: spawn a webview binary if present, else hand the URL to the system browser.
function openWindow(url) {
  if (!shouldOpenWindow()) {
    console.info("[abide:bundle] window-open skipped (headless/CI); app at", url);
    return;
  }
  const webview = probeWebview();
  if (webview) {
    console.info("[abide:bundle] opening system webview:", webview, "->", url);
    Bun.spawn([webview, url], { stdio: ["inherit", "inherit", "inherit"] });
    return;
  }
  const opener =
    process.platform === "darwin" ? ["open", url]
    : process.platform === "win32" ? ["cmd", "/c", "start", "", url]
    : ["xdg-open", url];
  console.info("[abide:bundle] no native webview found — falling back to system browser:", url);
  Bun.spawn(opener, { stdio: ["inherit", "inherit", "inherit"] });
}

async function main() {
  console.info(\`[abide:bundle] "\${WINDOW.title ?? "abide"}" (\${WINDOW.width ?? 1024}x\${WINDOW.height ?? 768})\`);
  let server;
  if (!REMOTE_URL) {
    // Self-host: boot the embedded app server with the bundle marker set.
    server = Bun.spawn(["abide", "start", "--port", String(PORT)], {
      env: { ...process.env, ABIDE_BUNDLED: "1" },
      stdio: ["inherit", "inherit", "inherit"],
    });
    // Give the server a moment to bind before pointing the window at it.
    await Bun.sleep(500);
  }
  openWindow(APP_URL);
  if (server) await server.exited;
}

main();
`;
}
