/*
Every standard HTML element name (lowercase), plus the two foreign-content roots
`svg`/`math`. A component wrapper tag that collides with one of these is a real
element with a content model and parser quirks — `<button>`/`<a>` reject interactive
descendants, table/list/select families foster or auto-close non-conforming children,
void elements self-close, and `<svg>`/`<math>` switch the parser into SVG/MathML
namespace so the wrapper's HTML children break out (foster-parent) of it entirely —
so the parser reparents the component's own markup out of the wrapper and hydration
claims `null`. `componentWrapperTag` remaps any such name to a transparent custom
element instead. Pure SVG/MathML descendant names (`circle`, `path`, `mrow`, …) are
NOT here: in HTML context they are inert unknown elements that hold children fine, so
a `<Circle>` component stays as-is like any non-element name. Superset of VOID_TAGS
(which the parser/SSR still use for self-closing); this set is only the
wrapper-safety check.
*/
export const HTML_TAGS: ReadonlySet<string> = new Set([
    'a',
    'abbr',
    'address',
    'area',
    'article',
    'aside',
    'audio',
    'b',
    'base',
    'bdi',
    'bdo',
    'blockquote',
    'body',
    'br',
    'button',
    'canvas',
    'caption',
    'cite',
    'code',
    'col',
    'colgroup',
    'data',
    'datalist',
    'dd',
    'del',
    'details',
    'dfn',
    'dialog',
    'div',
    'dl',
    'dt',
    'em',
    'embed',
    'fieldset',
    'figcaption',
    'figure',
    'footer',
    'form',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'head',
    'header',
    'hgroup',
    'hr',
    'html',
    'i',
    'iframe',
    'img',
    'input',
    'ins',
    'kbd',
    'label',
    'legend',
    'li',
    'link',
    'main',
    'map',
    'mark',
    'math',
    'menu',
    'meta',
    'meter',
    'nav',
    'noscript',
    'object',
    'ol',
    'optgroup',
    'option',
    'output',
    'p',
    'param',
    'picture',
    'pre',
    'progress',
    'q',
    'rp',
    'rt',
    'ruby',
    's',
    'samp',
    'script',
    'search',
    'section',
    'select',
    'slot',
    'small',
    'source',
    'span',
    'strong',
    'style',
    'sub',
    'summary',
    'sup',
    'svg',
    'table',
    'tbody',
    'td',
    'template',
    'textarea',
    'tfoot',
    'th',
    'thead',
    'time',
    'title',
    'tr',
    'track',
    'u',
    'ul',
    'var',
    'video',
    'wbr',
])
