/* The banner every generated abide `.d.ts` carries, warning off hand edits. */
const DTS_BANNER = '// Generated by abide. Do not edit by hand.'

/*
Writes a generated `.d.ts` to `src/.abide/<name>.d.ts` (the path the consumer's
src tsconfig include picks up), wrapping `body` in the shared banner + the
`export {}` footer that makes the file a module. The three codegen writers
(routes, rpc, public assets) differ only in `body`, so the envelope lives here.
*/
export async function writeDts(cwd: string, name: string, body: string): Promise<void> {
    await Bun.write(`${cwd}/src/.abide/${name}.d.ts`, `${DTS_BANNER}\n${body}\n\nexport {}\n`)
}
