/* The banner every generated abide `.d.ts` carries, warning off hand edits. */
const DTS_BANNER = '// Generated by abide. Do not edit by hand.'

/*
Writes a generated `.d.ts` to `src/.abide/<name>.d.ts` (the path the consumer's
src tsconfig include picks up), wrapping `body` in the shared banner + the
`export {}` footer that makes the file a module. All codegen writers (routes, rpc, publicAssets, testRpc, testSockets, health)
differ only in `body`, so the envelope lives here.
*/
export async function writeDts(cwd: string, name: string, body: string): Promise<void> {
    const next = `${DTS_BANNER}\n${body}\n\nexport {}\n`
    const file = Bun.file(`${cwd}/src/.abide/${name}.d.ts`)
    // Skip the write when byte-identical — an unchanged rebuild (the common case)
    // otherwise bumps mtime every save, forcing the editor's TS server to re-typecheck.
    if ((await file.exists()) && (await file.text()) === next) {
        return
    }
    await Bun.write(file, next)
}
