/*
Generates src/ui/cookbookIndex.generated.ts — the searchable cookbook index.

The cookbook is two hierarchies: cookbookSections.ts curates the sections and
sub-page labels; each sub-page's `page.abide` holds the actual recipes as <Recipe
task=… gap=…/> tags. This script folds them together so the cookbook page can both
browse the tree and search every recipe by task, deep-linking a hit to href#anchor
(the anchor is slugifyTask(task), the same id Recipe.abide stamps on its article).

Run: `bun run cookbook:index` (from examples/kitchen-sink). Re-run after adding or
renaming recipes, or editing cookbookSections.ts.
*/
import { cookbookSections } from '../src/ui/cookbookSections.ts'
import { slugifyTask } from '../src/ui/slugifyTask.ts'

const PAGES_ROOT = new URL('../src/ui/pages', import.meta.url)
const OUTPUT = new URL('../src/ui/cookbookIndex.generated.ts', import.meta.url)

type Recipe = { task: string; anchor: string; gap: boolean }
type IndexPage = { href: string; label: string; recipes: Recipe[] }
type IndexSection = { title: string; blurb: string; pages: IndexPage[] }

// Pull every recipe out of one sub-page in document (display) order. Each <Recipe
// tag opens a chunk that runs to the next tag; `task="…"` is a plain double-quoted
// attribute (no recipe embeds a `"` there) and `gap={true}` badges an honest gap.
function extractRecipes(fileText: string): Recipe[] {
    const recipes: Recipe[] = []
    const chunks = fileText.split('<Recipe')
    for (let i = 1; i < chunks.length; i++) {
        const chunk = chunks[i]
        const taskMatch = chunk.match(/task="([^"]*)"/)
        if (!taskMatch) {
            throw new Error(`<Recipe> with no task="…" attribute (chunk ${i})`)
        }
        const task = taskMatch[1]
        recipes.push({ task, anchor: slugifyTask(task), gap: chunk.includes('gap={true}') })
    }
    return recipes
}

// href '/cookbook/x/y' → the on-disk page.abide under src/ui/pages/.
function pageFileFor(href: string): URL {
    return new URL(`.${href}/page.abide`, `${PAGES_ROOT}/`)
}

let recipeCount = 0
const index: IndexSection[] = []
for (const section of cookbookSections) {
    const pages: IndexPage[] = []
    for (const page of section.pages) {
        const file = pageFileFor(page.href)
        const text = await Bun.file(file)
            .text()
            .catch(() => {
                throw new Error(`missing cookbook page for ${page.href} (${file.pathname})`)
            })
        const recipes = extractRecipes(text)
        if (recipes.length === 0) {
            console.warn(`⚠ ${page.href} has zero recipes`)
        }
        recipeCount += recipes.length
        pages.push({ href: page.href, label: page.label, recipes })
    }
    index.push({ title: section.title, blurb: section.blurb, pages })
}

const banner = `/*
 * GENERATED by scripts/cookbookIndex.ts — do not edit by hand.
 * Curation lives in cookbookSections.ts; recipes are parsed from each
 * cookbook sub-page. Regenerate with \`bun run cookbook:index\`.
 */`

const body = `export type CookbookRecipe = { task: string; anchor: string; gap: boolean }
export type CookbookIndexPage = { href: string; label: string; recipes: CookbookRecipe[] }
export type CookbookIndexSection = { title: string; blurb: string; pages: CookbookIndexPage[] }

export const cookbookIndex: CookbookIndexSection[] = ${JSON.stringify(index, undefined, 4)}
`

await Bun.write(OUTPUT, `${banner}\n\n${body}`)
console.log(
    `✓ cookbookIndex.generated.ts — ${index.length} sections, ` +
        `${index.reduce((n, s) => n + s.pages.length, 0)} sub-pages, ${recipeCount} recipes`,
)
