name = "Abide"
grammar = "html"
path_suffixes = ["abide"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>"

brackets = [
  { start = "<", end = ">", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
