// GENERATED by `abide build`. This is the whole of what the browser receives for
// src/server/rpc/invoices.ts — a method, a mount-relative address, a description.
// The handler body, the `#server/database` import and anything that module did at
// load time are not here, because this file was never derived from that one.
import { rpc } from 'abide/runtime'

export const getInvoice = rpc({
    method: 'GET',
    address: '/__abide/rpc/invoices/getInvoice',
    description: undefined,
})
