// The generated `src/.abide/health.d.ts` text (CO2.4). The end-to-end proof that it actually TYPES
// anything is `writeHealthCompanion.test.ts`, which compiles a fixture app against it; this file
// covers the two shapes it can take.

import { describe, expect, test } from 'bun:test'
import { healthCompanion } from './healthCompanion.ts'

describe('healthCompanion', () => {
    test('no src/app.ts — a module that augments nothing', () => {
        const text = healthCompanion(false)
        expect(text).toStartWith('// Generated by abide. Do not edit by hand.')
        expect(text).toContain('src/app.ts absent')
        expect(text).not.toContain('declare module')
        // Still a MODULE: a file with no import/export is a global script, and a stale one left in the
        // program could collide with app declarations.
        expect(text).toContain('export {}')
    })

    test('with src/app.ts — augments the module an APP names, not a path into the package', () => {
        const text = healthCompanion(true)
        expect(text).toContain("declare module 'abide/shared/health'")
        expect(text).toContain('interface HealthAugmentation')
        expect(text).toContain("import type * as app from '../app.ts'")
    })

    test('the derivation is conditional, so an app with no onHealth export still compiles', () => {
        // A `typeof app extends { onHealth: … }` probe rather than a direct `ReturnType<typeof
        // onHealth>`: the latter is a hard error in an app whose app.ts exports only middleware, which
        // is most of them.
        expect(healthCompanion(true)).toContain('typeof app extends { onHealth:')
        expect(healthCompanion(true)).toContain(': unknown')
    })

    test('a hook with parameters or a promise return still derives', () => {
        const text = healthCompanion(true)
        // `(...args: never[])` accepts any signature — a zero-arg hook is assignable to it, and so is
        // one that took an argument by mistake, which must degrade to its return type rather than to
        // `unknown`. `Awaited` collapses an async hook.
        expect(text).toContain('(...args: never[]) => infer Fields')
        expect(text).toContain('Awaited<Fields>')
    })
})
