// The generated `src/.abide/health.d.ts` — what makes `(await health()).db` a typed read in the app
// that declares `onHealth` and a compile error in the app that does not (CO2.4).
//
// PURE TEXT, and deliberately so: the whole derivation is `Awaited<ReturnType<typeof onHealth>>`, which
// is TypeScript's own work, done in the app's own project. Nothing here reads a type, so there is no
// tsgo pass to pay for and nothing to go stale between the generated file and the source it describes —
// edit `onHealth`'s return and the companion already says the new thing. The only fact this needs from
// disk is whether `src/app.ts` EXISTS; whether it exports `onHealth`, and what that export returns, are
// both decided at type level by the conditional below (an app with no hook, or a hook returning a
// non-object, contributes `unknown`, and `T & unknown` is `T`).
//
// Written on disk rather than into the check lane's virtual overlay, unlike the `<file>.abide.d.ts`
// component companions: those exist only to type a `.abide` import that only `abide check`/`lsp`
// resolve, while this one has to be seen by the app author's own editor and `tsc`, neither of which
// runs through abide. `src/.abide/` is the reserved generated-types namespace and is gitignored.
//
// THE TSCONFIG HAS TO NAME IT. A TypeScript `include` wildcard never descends into a DOT-directory —
// `**/` expands to `(?:/[^/.][^/]*)*` — so `"include": ["src/**/*.ts"]` silently does not match
// `src/.abide/health.d.ts`, and an augmentation in a file outside the program augments nothing. There
// is no diagnostic for that: the app just goes on seeing the bare baseline, which is exactly what it
// saw before this existed. Hence the literal `"src/.abide/*.d.ts"` entry in the scaffolded tsconfig,
// and hence `writeHealthCompanion` warns when it writes a companion no tsconfig is going to read.

// The module specifier the augmentation targets. It must be the string an APP writes, not a relative
// path into the package: TypeScript matches an augmentation by resolved module, and the app resolves
// this one through the `abide` package's `./shared/*` export.
const HEALTH_MODULE = 'abide/shared/health'

export function healthCompanion(hasAppModule: boolean): string {
    const header = '// Generated by abide. Do not edit by hand.\n'
    if (!hasAppModule) {
        return `${header}// src/app.ts absent — health() carries only the framework fields.\n\nexport {}\n`
    }
    return `${header}// Types health() with this app's onHealth fields, merged over the framework baseline.
// An app with no onHealth export contributes nothing — the conditional in HealthFields resolves to
// unknown, and the document stays the baseline.

import type * as app from '../app.ts'

declare module '${HEALTH_MODULE}' {
    interface HealthAugmentation {
        onHealth: typeof app extends { onHealth: (...args: never[]) => infer Fields }
            ? Awaited<Fields>
            : unknown
    }
}
`
}
