import { claimChild } from '../runtime/claimChild.ts'
import { RENDER } from '../runtime/RENDER.ts'

/*
Parsed-once `<template>` per unique static-skeleton string, reused across every
mount. A `<template>` (not a detached `<div>`) so table/select content parses by
the real content model, exactly as the browser parsed the server markup.
*/
const TEMPLATES = new Map<string, HTMLTemplateElement>()

function templateFor(html: string): HTMLTemplateElement {
    let template = TEMPLATES.get(html)
    if (template === undefined) {
        template = document.createElement('template')
        template.innerHTML = html
        TEMPLATES.set(html, template)
    }
    return template
}

/*
Appends a fully-static subtree (one or more top-level nodes) under `parent` — what
the compiler emits in place of the imperative `openChild`/`setAttribute`/
`appendStatic` chain when an element subtree carries no bindings, control flow, or
listeners. The skeleton string is generated by the same rules as the SSR back-end,
so it is byte-identical to the server markup.

Create mode: clone the cached template once per mount — a single deep clone (native
in the browser) instead of N create/append calls. Hydrate mode: nothing is built;
the server already rendered this exact markup, so it only advances the parent's
claim cursor past the run's top-level nodes (nothing inside binds, so none need
claiming individually). The node count comes from the parsed template, which has
the same top-level node count as the server markup.
*/
// @readme plumbing
export function cloneStatic(parent: Node, html: string): void {
    const template = templateFor(html)
    const hydration = RENDER.hydration
    if (hydration !== undefined) {
        let node = claimChild(hydration, parent)
        let remaining = template.content.childNodes.length
        while (remaining > 0 && node !== null) {
            node = node.nextSibling
            remaining -= 1
        }
        hydration.next.set(parent, node)
        return
    }
    for (const child of template.content.childNodes) {
        parent.appendChild(child.cloneNode(true))
    }
}
